
services:
  # Наша база данных
  db:
    image: postgres:15-alpine
    container_name: scrimba_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scrimba_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Твой Go бэкенд
  app:
    build: .
    container_name: scrimba_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_URL: "host=db user=user password=password dbname=scrimba_db port=5432 sslmode=disable"
      HF_TOKEN: "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" # Твой токен здесь
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/app 
    depends_on:
      - db

volumes:
  postgres_data:
